{% set name = "spatialdata" %}
{% set version = "0.6.1" %}
{% set python_min = "3.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/spatialdata-{{ version }}.tar.gz
  sha256: d0295feb90b16a6802f13e85780243fe7aecb838b44ba433c304805eac01d555

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - hatch-vcs
    - hatchling
    - pip
    - python {{ python_min }},<3.13
  run:
    - anndata >=0.9.1
    - click
    - dask >=2024.10.0,<=2024.11.2
    - dask-image
    - datashader
    - fsspec
    - geopandas >=0.14
    - multiscale-spatial-image 2.0.3
    - networkx
    - numba >=0.55.0
    - numpy
    - ome-zarr >=0.12.2
    - pandas
    - pooch
    - pyarrow
    - python >={{ python_min }},<3.13
    - pytorch
    - rich
    - scikit-image
    - scipy
    - shapely >=2.0.1
    - spatial-image >=1.2.3
    - typing-extensions >=4.8.0
    - universal-pathlib >=0.2.6
    - xarray >=2024.10.0
    - xarray-schema
    - xarray-spatial >=0.3.5
    - zarr >=3.0.0

test:
  imports:
    - spatialdata
  commands:
    - pip list
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pypi.org/project/spatialdata
  summary: Spatial data format.
  license: BSD-3-Clause
  license_file: LICENSE
  dev_url: https://github.com/scverse/spatialdata

extra:
  recipe-maintainers:
    - melonora
    - jdblischak
    - LucaMarconato
    - giovp
    - goanpeca
    - kevinyamauchi
