{% set name = "spatialdata" %}
{% set version = "0.4.0" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/spatialdata-{{ version }}.tar.gz
  sha256: 6c7d1abf366fd5e61e9c9b489d04ad644a9609489588fa3436e59f4c96b67846

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - hatch-vcs
    - hatchling
    - pip
    - python {{ python_min }},<3.13
  run:
    - anndata >=0.9.1
    - click
    - dask-core >=2024.4.1,<=2024.11.2
    - dask-image
    - datashader
    - fsspec
    - geopandas >=0.14
    - multiscale-spatial-image >=2.0.2
    - networkx
    - numba >=0.55.0
    - numpy
    - ome-zarr >=0.8.4
    - pandas
    - pooch
    - pyarrow
    - python >={{ python_min }},<3.13
    - pytorch
    - rich
    - scikit-image
    - scipy
    - shapely >=2.0.1
    - spatial-image >=1.1.0
    - typing-extensions >=4.8.0
    - xarray >=2024.10.0
    - xarray-schema
    - xarray-spatial >=0.3.5
    - xarray-dataclasses >=1.8.0
    - zarr <3

test:
  imports:
    - spatialdata
  commands:
    - pip list
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pypi.org/project/spatialdata
  summary: Spatial data format.
  license: BSD-3-Clause
  license_file: LICENSE
  dev_url: https://github.com/scverse/spatialdata

extra:
  recipe-maintainers:
    - jdblischak
    - LucaMarconato
    - giovp
    - goanpeca
    - kevinyamauchi
