{% set name = "spatialdata" %}
{% set version = "0.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/spatialdata-{{ version }}.tar.gz
  sha256: 11f824f086c4cb5f6a89ddf8784d590a0f88906d2c88a52b8db1b848f0d4348c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - hatch-vcs
    - hatchling
    - pip
    - python >=3.9
  run:
    - anndata >=0.9.1
    - click
    - dask-core
    - dask-image
    - fsspec <=2023.6
    - geopandas
    - multiscale-spatial-image 0.11.2
    - networkx
    - numpy
    - ome-zarr >=0.7.0
    - pandas
    - pyarrow
    - pygeos
    - python >=3.9
    - pytorch
    - rich
    - scikit-image
    - scipy
    - shapely >=2.0.1
    - spatial-image 0.3.0
    - typing-extensions >=4.8.0
    - xarray >=2023.12.0
    - xarray-datatree
    - xarray-schema
    - xarray-spatial >=0.3.5
    - zarr

test:
  imports:
    - spatialdata
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/spatialdata
  summary: Spatial data format.
  license: BSD-3-Clause
  license_file: LICENSE
  dev_url: https://github.com/scverse/spatialdata

extra:
  recipe-maintainers:
    - LucaMarconato
    - giovp
    - goanpeca
    - kevinyamauchi
