{% set name = "spatialdata" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/spatialdata-{{ version }}.tar.gz
  sha256: 9215dd5171ac9ac0eed01a265f43092c8bdb760f0b1e994795fa274c5c638611

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - hatch-vcs
    - hatchling
    - pip
    - python >=3.10
  run:
    - anndata >=0.9.1
    - click
    - dask-image
    - dask-core >=2024.4.1,<=2024.11.2
    - datashader
    - fsspec
    - geopandas >=0.14
    - multiscale-spatial-image >=2.0.2
    - networkx
    - numba
    - numpy
    - ome-zarr >=0.8.4
    - pandas
    - pooch
    - pyarrow
    - python >=3.10
    - pytorch
    - rich
    - shapely >=2.0.1
    - spatial-image >=1.1.0
    - scikit-image
    - scipy
    - typing-extensions >=4.8.0
    - xarray >=2024.10.0
    - xarray-schema
    - xarray-spatial >=0.3.5
    - zarr <3

test:
  imports:
    - spatialdata
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/spatialdata
  summary: Spatial data format.
  license: BSD-3-Clause
  license_file: LICENSE
  dev_url: https://github.com/scverse/spatialdata

extra:
  recipe-maintainers:
    - LucaMarconato
    - giovp
    - goanpeca
    - kevinyamauchi
