{% set name = "spatialdata" %}
{% set version = "0.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/spatialdata-{{ version }}.tar.gz
  sha256: 7c00958bfabea34d8cf200ccd24f0e14b7873ff84ccf37b5a6f7a1d747728558

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - hatch-vcs
    - hatchling
    - pip
    - python >=3.9
  run:
    - anndata >=0.9.1
    - click
    - dask-core >=2024.4.1
    - dask-image
    - fsspec <=2023.6
    - geopandas >=0.14
    - multiscale-spatial-image >=1.0.0
    - networkx
    - numpy
    - ome-zarr >=0.8.4
    - pandas
    - pyarrow
    - pygeos
    - python >=3.9
    - pytorch
    - rich
    - scikit-image
    - scipy
    - shapely >=2.0.1
    - spatial-image >=1.0.0
    - typing-extensions >=4.8.0
    - xarray >=2023.12.0
    - xarray-datatree
    - xarray-schema
    - xarray-spatial >=0.3.5
    - zarr
    - pooch
    - tqdm

test:
  imports:
    - spatialdata
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/spatialdata
  summary: Spatial data format.
  license: BSD-3-Clause
  license_file: LICENSE
  dev_url: https://github.com/scverse/spatialdata

extra:
  recipe-maintainers:
    - LucaMarconato
    - giovp
    - goanpeca
    - kevinyamauchi
