{% set name = "spatialdata" %}
{% set version = "0.2.5" %}
{% set python_min = "3.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/spatialdata-{{ version }}.tar.gz
  sha256: 4ed8f30347a524548ce54f5957383dd8165ac27ead1c02c68be322854556d17f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - hatch-vcs
    - hatchling
    - pip
    - python {{ python_min }}
  run:
    - anndata >=0.9.1
    - click
    - dask-core >=2024.4.1,<2025
    - dask-image
    - datashader
    - fsspec <=2023.6
    - geopandas >=0.14
    - multiscale-spatial-image >=1.0.0,<2.0.0
    - networkx
    - numba
    - numpy
    - ome-zarr >=0.8.4,<0.10.3
    - pandas
    - pooch
    - pyarrow
    - python >={{ python_min }}
    - pytorch
    - rich
    - scikit-image
    - scipy
    - shapely >=2.0.1
    - spatial-image >=1.1.0
    - typing-extensions >=4.8.0
    - xarray >=2023.12.0,<2024.10.0
    - xarray-datatree
    - xarray-schema
    - xarray-spatial >=0.3.5
    - zarr

test:
  imports:
    - spatialdata
  commands:
    - pip list
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pypi.org/project/spatialdata
  summary: Spatial data format.
  license: BSD-3-Clause
  license_file: LICENSE
  dev_url: https://github.com/scverse/spatialdata

extra:
  recipe-maintainers:
    - jdblischak
    - LucaMarconato
    - giovp
    - goanpeca
    - kevinyamauchi
