{% set name = "spatialdata" %}
{% set version = "0.2.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/spatialdata-{{ version }}.tar.gz
  sha256: 48a37f9d03274c0967d6e4ba2bf7b826a8d2faff06f0ee8de5db76411e0e6bed

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - hatch-vcs
    - hatchling
    - pip
    - python >=3.9
  run:
    - anndata >=0.9.1
    - click
    - dask-core >=2024.4.1,<2024.11.0
    - dask-image
    - datashader
    - fsspec <=2023.6
    - geopandas >=0.14
    - multiscale-spatial-image >=1.0.0
    - networkx
    - numpy
    - ome-zarr >=0.8.4,<0.10.3
    - pandas
    - pooch
    - pyarrow
    - python >=3.9
    - pytorch
    - rich
    - scikit-image
    - scipy
    - shapely >=2.0.1
    - spatial-image >=1.0.0
    - typing-extensions >=4.8.0
    - xarray >=2023.12.0,<2024.10
    - xarray-datatree
    - xarray-schema
    - xarray-spatial >=0.3.5
    - zarr

test:
  imports:
    - spatialdata
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/spatialdata
  summary: Spatial data format.
  license: BSD-3-Clause
  license_file: LICENSE
  dev_url: https://github.com/scverse/spatialdata

extra:
  recipe-maintainers:
    - jdblischak
    - LucaMarconato
    - giovp
    - goanpeca
    - kevinyamauchi
